CM Class Reference
CM Class.
#include <cm.h>
Public Member Functions
CM ()
Class constructor.
~CM ()
Destructor.
void set_parameters_from_file (char *fname)
Setup parameters for the CM encoder/decoder and also calculate the bit and symbol block lengths based on a control file.
void set_parameters (const int mode_in, const int k_in, const int n_in, const int L_in, const int Terminated_in, const int iterations_in, const int decoder_type_in, const int no_of_symbols_in, const int modulation_type_in, const int interleaver_mode_in)
Setup parameters for the CM encoder/decoder and also calculate the bit and symbol block lengths.
void reset_CM (int new_no_of_symbols)
reset symbol block length and interleaver for variable length coded modulation
void reset_CM_iteration (int new_iterations)
reset number of turbo iterations for variable-iterated TTCM and BICMID
void initialise ()
Initialise CM: allocate memory and initialise coder, modulator (modulation) & interleaver.
int encode (bvec b_Input_bits, ivec &i_Output_symbols)
CM encoder: encode and channel interleave.
int encode_bits (bvec b_Input_bits, ivec &i_Output_bits)
CM encoder: encode and channel interleave.
int decode (bvec &b_decoded_bits)
CM decoder: channel deinterleave and decode.
vec decode (bvec &b_decoded_bits, vec cm_apr_databits_llr)
CM decoder: channel deinterleave and decode.
int decode_using_Pr (bvec &b_decoded_bits, mat Pr)
CM decoder: channel deinterleave and decode.
int decode_using_PrIQ (bvec &b_decoded_bits, mat PrI, mat PrQ)
CM decoder: channel deinterleave and decode.
cvec modulate_symbols (ivec i_encoded_symbols)
CM modulator.
void demodulate_soft_symbols (cvec c_received_signals, double _2sigma2)
CM demodulator for AWGN channel.
void demodulate_soft_symbols (cvec c_received_signals, cvec channel_gains, double _2sigma2)
CM demodulator for flat Rayleigh fading channel.
void demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double _2sigma2, vec beta, vec var_n, vec pow_s, vec mu_n)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: relay signals only.
void demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: perfect relay.
void demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd, vec beta, vec var_n, vec pow_s, vec mu_n)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: soft relay.
void demodulate_soft_symbols_relay_aaf (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd, cvec channel_gains_sr, vec factor)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: Amplify And Forward (AAF).
void decode_symbol (mat Apo, ivec &symbols, int N, int M)
decode symbol based on symbol's a-poteriori probability
void print_parameters (FILE *fp)
print parameters to a file pointer.
void print_parameters (fstream &fs)
print parameters to a file stream.
void print_coding_tables (FILE *fp)
print coding tables to a file pointer.
void print_coding_tables (fstream &fs)
print coding tables to a file stream.
char * get_result_filename ()
return the result filename.
int get_sym_length ()
return the output coded symbol vector length.
int get_info_sym_length ()
return the input data symbol vector length
int get_coded_bit_length ()
return the output coded bit vector length
int get_info_bit_length ()
return the input data bit vector length
int get_termination_bit_length ()
return the input data bit vector length
int get_iterations ()
return the number of turbo iterations
int get_coder_mode ()
return the coder mode
mat get_Pr ()
return the channel symbol probability from demodulator.
mat get_PrI ()
return the In-phase channel symbol probability from demodulator.
mat get_PrQ ()
return the Quadrature-phase channel symbol probability from demodulator.
mat get_OPr ()
return the coded symbol a-posteriori probability after decoding
mat get_normal_domain_OPr ()
return the coded symbol a-posteriori probability after decoding : normal domain
mat * get_Coded_Bit_OPr ()
return the coded bits a-posteriori probability after decoding
mat * get_Data_Bit_OPr ()
return the data bits a-posteriori probability after decoding
double get_coderate ()
return the actual coding rate
int get_info_bps ()
return the number of information bits per modulated symbol
int get_bps ()
return the number of bits per modulated symbol
double compute_Eb (double Es)
calculate SNR per databit Eb, given the symbol energy Es: $ Eb = Es/(R*BPS) $ where R=coderate, BPS=bits per modulated symbol.
vec get_data_llr ()
calculate the aposteriori log likelihood ratio for each data bits after decoding
vec get_data_extr_llr ()
cvec get_SymbolMapping ()
get the mapping table of the complex symbol
vec get_SymbolMappingI ()
get the In-phase mapping table of the complex symbol
vec get_SymbolMappingQ ()
get the Quadrature-phase mapping table of the complex symbol
void SymProb_to_LLR (int N, int bps, vec &LLR, mat SymPr)
convertion of Symbol probability in Log domain to LLR
void LLR_to_SymProb (int N, int bps, vec LLR, mat &SymPr)
convertion of Log-Likelihood Ratio (LLR) to Symbol probability in Log domain
void LLR_to_Prob (int N, int bps, vec LLR, mat *&BitPr)
convertion of Log-Likelihood Ratio (LLR) to Bit probability in Log domain
void Prob_to_LLR (int N, int bps, vec &LLR, mat *BitPr)
convertion of Bit probability in Log domain to LLR
Protected Member Functions
void allocate_memory_tcm ()
allocate memory for TCM coder
void allocate_memory_ttcm ()
allocate memory for TTCM coder
void allocate_memory_bicm ()
allocate memory for BICM/BICMID coder
void initModulation_SP ()
initialise SP based modulator
void initModulation_GRAY ()
initialise GRAY coded based modulator
void initTCM ()
initialise TCM/TTCM coder
void initCC ()
initialise BICM coder (rate 1/2, 2/3 & 3/4): non-binary Convolutional code
void initPunctureCC ()
initialise BICM coder (rate 5/6): employ puncturing on rate 1/2 mother code
void get_gen_poly ()
get generator polynomial from a predefined table for TCM/TTCM
void get_CC_poly ()
get generator polynomial and puncturing pattern from a predefined table for BICM/BICMID
void init_channel_interleaver (int no_of_symbols)
initialise channel interleaver: symbol interleaver (ON, OFF) or IQ interleaver (IQ_INTLV)
void free_channel_interleaver ()
Free Channel Interleaver memory.
void init_random_interleaver (int block_length, ivec &table, char *txt)
initialise random interleaver
void init_iq_tables ()
initialise In-phase Quadrature-phase random interleaver
void get_I_table ()
get In-phase table, used by init_iq_tables()
void get_Q_table ()
get Quadrature-phase table, used by init_iq_tables()
void init_TTCM_interleaver ()
initialise TTCM interleaver: Odd Even Separated (oes) symbol intereaver
void init_OES_interleaver (int block_length, ivec &i_table)
initialise Odd-Even-Separated symbol interleaver for TTCM
int intlv_termination_locat (int block_length, int L, ivec &i_table, ivec &last)
find termination locations for 2nd encoder of TTCM used by init_OES_interleaver()
void TCMEnc (ivec, ivec &)
TCM encoder.
void TurboTCMEnc (ivec, ivec &)
TTCM encoder.
void BICMEnc (ivec, ivec &)
BICM encoder.
void BICMEnc_Puncture (ivec, ivec &)
punctured BICM encoder
double jacolog (double x, double y)
Jacobian logarithmic summation: based on the decoder_type obtions.
void log_mapdec (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat *Ip, mat &Apo, mat &OPr)
Logarithmic MAP decoder for TCM.
void log_TTCM_dec (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat *Ip1, mat *Ip2, mat &Apo, mat &OPr, mat &OPr2)
Logarithmic MAP decoder for TTCM, assumming no Apr information from other source.
void log_TTCM_dec_apr (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat *Ip1, mat *Ip2, mat &Apo, mat &OPr, mat &OPr2)
Logarithmic MAP decoder for TTCM, can be used for joint CM and source coding where Apr is provided by the source decoder.
void SISO_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat *Apr_coded_bit, mat *&Apo_coded_bit, mat *&Apo_data_bit, mat &Apo_dataword, int Terminated, int frame_index)
Logarithmic SISO(MAP) decoder for BICM.
void SISO_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat Apr_codeword, mat Apr_dataword, mat &Apo_codeword, mat &Apo_dataword, int Terminated, int frame_index)
Logarithmic SISO(MAP) decoder for any coding scheme.
void BICM_ID_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat *Apr_coded_bit, mat *Apr_data_bit, mat *&Apo_coded_bit, mat *&Apo_data_bit, mat &Apo_dataword, int Terminated)
Logarithmic SISO(MAP) decoder for BICM/BICMID.
void BICM_ID_dec_log_pun (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat *Apr_coded_bit, mat *Apr_data_bit, mat *&Apo_coded_bit, mat *&Apo_data_bit, mat &Apo_dataword, int Terminated)
Logarithmic SISO(MAP) decoder for BICM/BICMID employing puncturing.
void extrinsic_demod_log (int N, int lC, int C, mat *Apo_coded_bit, mat Pr, mat *&Extr_coded_bit, int frame_index)
demodulator of BICMID which outputs the extrinsic probability of coded bits
void depuncture (mat *Apr_coded_bit, mat *&p_Apr_coded_bit, int N, int dataword_length, int codeword_length, ivec puncture, int p_lC, int frame_index)
depuncturer for punctured BICM code
void puncture (mat *&Apo_coded_bit, mat *p_Apo_coded_bit, int N, int dataword_length, int codeword_length, ivec puncture, int p_lC, int frame_index)
puncturer for punctured BICM code
void get_Apo_dataword (mat &Apo_dataword, mat *&Apo_data_bit, mat *p_Apo_data_bit, int N, int dataword_length, int p_lD)
calculate dataword's and databit's a-posteriori probability from coded bit's a-posteriori probability of decoder
void get_p_Apr_data_bit (mat *&p_Apr_data_bit, mat *Apr_data_bit, int N, int dataword_length, int p_lD)
calculate the databit's a-priori probability for punctured BICM decoding
void intlvi (ivec x, ivec &y, int block_length, ivec i_table)
interleaving integer vector of length block_length based on i_table
void de_intlvi (ivec x, ivec &y, int block_length, ivec i_table)
deinterleaving integer vector of length block_length based on i_table
void intlvd_2d (mat x, mat &y, int block_length, ivec i_table)
interleaving double matrix (2-dimension) of length block_length based on i_table
void de_intlvd_2d (mat x, mat &y, int block_length, ivec i_table)
deinterleaving double matrix (2-dimension) of length block_length based on i_table
void intlvm_3d (mat *x, mat *&y, int block_length, ivec i_table)
interleaving double *matrix (3-dimension) of length block_length based on i_table
void de_intlvm_3d (mat *x, mat *&y, int block_length, ivec i_table)
deinterleaving double *matrix (3-dimension) of length block_length based on i_table
void bit_intlvi (imat x, imat &y, int block_length, ivec i_table, int index)
interleaving index-th bit's integer vector (row of imat) of length block_length based on i_table
void bit_de_intlvi (imat x, imat &y, int block_length, ivec i_table, int index)
deinterleaving index-th bit's integer vector (row of imat) of length block_length based on i_table
void bit_intlvm_3d (mat *x, mat *&y, int block_length, int m, ivec i_table, int index)
interleaving index-th bit's double *matrix (3-dimension) of length block_length based on i_table
void bit_de_intlvm_3d (mat *x, mat *&y, int block_length, int m, ivec i_table, int index)
deinterleaving index-th bit's double *matrix (3-dimension) of length block_length based on i_table
void iq_intlvc (cvec x, cvec &y, int block_length, ivec i_table, ivec q_table)
interleaving In-phase and Quadrature-phase of a complex vector
void iq_de_intlvc (cvec x, cvec &y, int block_length, ivec i_table, ivec q_table)
deinterleaving In-phase and Quadrature-phase of a complex vector
void demodulate_soft_symbols_IQ (cvec c_received_signals, double _2sigma2)
IQ demodulator for AWGN channel based on complex received_signals and 2*sigma^2. PrI, PrQ and Pr are updated.
void demodulate_soft_symbols_IQ (cvec c_received_signals, cvec channel_gains, double _2sigma2)
IQ demodulator for flat Rayleigh fading channel based on complex received_signals and 2*sigma^2. PrI, PrQ and Pr are updated.
void compute_Pr_from_PrIQ (mat &Pr, mat PrI, mat PrQ)
computing Pr from PrI and PrQ
Protected Attributes
mat Pr
channel symbol probability from demodulator
mat OPr
coded symbol a-posteriori probability after decoding
mat OPr2
coded symbol a-posteriori probability after decoding of second decoder (for TTCM)
mat PrI
In-phase channel symbol probability from demodulator.
mat PrQ
Quadrature-phase channel symbol probability from demodulator.
struct modulation_param * modulation
modulator of CM
struct cm_interleaver_control * interleaver
interleaver of CM
struct TCM_parameters * tcm
TCM of CM.
struct TTCM_parameters * ttcm
TTCM of CM.
struct MAP_dec * map
MAP decoder for TCM and TTCM.
struct BICM_parameters * bicm
BICM of CM.
struct BICMID_parameters * bicmid
BICMID of CM.
struct SISO_dec * siso
SISO decoder for BICM and BICMID.
Private Member Functions
void Pr_to_BitPr_log (int N, int lM, mat Pr, mat *&BitPr, int frame_index)
Log-domain: compute bit probability BitPr from symbol probability Pr; N=total symbol, lM=bit per modulated symbol.
void BitPr_to_Pr_log (int N, int lM, mat &Pr, mat *BitPr, int frame_index)
Log-domain: compute symbol probability Pr from bit probability BitPr; N=total symbol, lM=bit per modulated symbol.
void symbol_to_bits (int word_length, int block_length, ivec symbols, imat &bits_block)
compute bit matrix (bits_block) from symbol vector (symbol); word_length=col block_length=row of bits_block
void bits_to_symbol (int word_length, int block_length, imat bits_block, ivec &symbols)
compute symbol vector (symbol) from bit matrix (bits_block); word_length=col block_length=row of bits_block
ivec symbol_to_bits_seq (int word_length, int block_length, ivec symbols)
compute bit vector of length=block_length*word_length from symbol vector
ivec bits_seq_to_symbol (int word_length, int block_length, ivec bits_seq)
compute symbol vector from bit vector of length=block_length*word_length
void s_error (const char *message)
printout error message and exit
void makebits (int s, int N, imat &bit1, imat &bit2)
Set Partitioning labelling for QAM.
double correct_rounding_error (double distance)
correct rounding error to the precision of 6 decimal places
int octal_to_decimal (int gen)
compute decimal number from octal number
Private Attributes
char result_filename [500]
name of result file
int mode
CM mode: TCM, TTCM, BICM, BICMID.
int modulation_type
modulation type: CPSK, CQAM
int interleaver_mode
interleaver mode: OFF, ON, IQ_INTLV
int Terminated
code termination: OFF, ON
int decoder_type
decoding type: CM_EXACT_LOG_MAP, CM_APPROX_LOG_MAP, CM_MAX_LOG_MAP
int k
length of dataword
int n
length of codeword
int L
code memory length
int iterations
number of turbo iterations
int max_no_of_symbols
maximum number of coded symbols in a block, for variable length CM
int no_of_symbols
number of coded symbols in a block
int no_of_info_symbols
number of information (input data) symbols in one block
int no_of_coded_bits
number of output coded bits in one block
int no_of_info_bits
number of information (input data) bits in one block
int no_of_tail_bits
number of termination (tail) bits in one block
int no_of_input_bits
number of input bits (no_of_info_bits + no_of_tail_bits) in one block
Detailed Description
CM Class.
This class provides four coded modulation schemes:
TCM, TTCM, BICM and BICMID.
Modulation modes available are M-QAM and M-PSK, where M=2^n is the modulation level. We have:
4-QAM, 16-QAM, 64-QAM (CQAM)
4-PSK, 8-PSK, 16-PSK, 64-PSK (CPSK)
Interleaver types available are:
symbol interleaver (ON, OFF) for TCM, TTCM
internal parallel bit interleavers for BICM and BICMID (always ON for BICM & BICMID)
IQ interleaver (IQ_INTLV) for TCM, TTCM, BICM, BICMID
Decoding in logarithmic domain is performed: decoder_type available are CM_EXACT_LOG_MAP, CM_APPROX_LOG_MAP, CM_MAX_LOG_MAP.
To set up a rate-3/4 (k=3, n=4) 16QAM TTCM having code memory 3, code termination, 4 turbo iteration, CM_APPROX_LOG_MAP decoder, 100 coded symbols (no_of_symbols), employ IQ-channel interleaver; the following code can be used:
  CM cm;
  cm.set_parameters(TTCM,3,4,3,ON,4,CM_APPROX_LOG_MAP,100,CQAM,IQ_INTLV);
  cm.initialise();
 See cm_test.cpp for more details.
Warning:
Modulation level = 2^n
Make sure that n=k+1; so that when compared CM to uncoded scheme
the modulation level is doubled but
experience no bandwidth expansion
no_of_info_bits=no_of_info_symbols*k, where
no_of_info_symbols=no_of_symbols
 if Terminated=OFF for all CM schemes
no_of_info_symbols=no_of_symbols-L
 if Terminated=ON for TCM, BICM & BICMID
no_of_info_symbols=no_of_symbols-2*L
 if Terminated=ON for TTCM
Definition at line 216 of file cm.h.
Member Function Documentation
void CM::set_parameters_from_file (char * fname)
Setup parameters for the CM encoder/decoder and also calculate the bit and symbol block lengths based on a control file.
Parameters:
fname the control file name.
Note: after reading the parameters from a control file, set_parameters() will be called.
Definition at line 53 of file cm.cpp.
References result_filename, FILESERVICE::scan_integer(), FILESERVICE::scan_text(), and set_parameters().
Referenced by main().
void CM::set_parameters (const int mode_in, const int k_in, const int n_in, const int L_in, const int Terminated_in, const int iterations_in, const int decoder_type_in, const int no_of_symbols_in, const int modulation_type_in, const int interleaver_mode_in)
Setup parameters for the CM encoder/decoder and also calculate the bit and symbol block lengths.
Parameters:
mode_in CM.mode: TCM, TTCM, BICM, BICMID
k_in dataword length
n_in codeword length
L_in code memory length
Terminated_in code termination: OFF, ON
iterations_in turbo iteration number, for TTCM and BICMID
decoder_type_in decoding type: CM_EXACT_LOG_MAP, CM_APPROX_LOG_MAP, CM_MAX_LOG_MAP
no_of_symbols_in number of coded symbols in a block
modulation_type_in modulator type: CPSK, CQAM
interleaver_mode_in interleaver mode: OFF, ON, IQ_INTLV (internal bit interleaver for BICM or BICMID is always ON)
Warning:
Modulation level = $ 2^{n\_in} $
Make sure that n_in=k_in+1; so that when compared CM to uncoded scheme
the modulation level is doubled but
experience no bandwidth expansion
Note:
k=k_in, n=n_in, L=L_in
if Terminated is OFF:
no_of_info_symbols=no_of_symbols_in
if Terminated is ON:
no_of_info_symbols=no_of_symbols_in-2*L (TTCM)
no_of_info_symbols=no_of_symbols_in-L (TCM, BICM & BICMID)
no_of_info_bits=no_of_info_symbols*k
no_of_coded_bits=no_of_symbols*n
no_of_tail_bits=(no_of_symbols-no_of_info_symbols)*k
Definition at line 79 of file cm.cpp.
References BICM, BICMID, CM_APPROX_LOG_MAP, CM_EXACT_LOG_MAP, CM_MAX_LOG_MAP, CPSK, CQAM, decoder_type, interleaver_mode, IQ_INTLV, iterations, k, L, max_no_of_symbols, mode, modulation_type, n, no_of_coded_bits, no_of_info_bits, no_of_info_symbols, no_of_input_bits, no_of_symbols, no_of_tail_bits, OFF, ON, s_error(), TCM, Terminated, and TTCM.
Referenced by set_parameters_from_file().
void CM::reset_CM (int new_no_of_symbols)
reset symbol block length and interleaver for variable length coded modulation
Parameters:
new_no_of_symbols new symbol block length (<= max_no_of_symbols).
Definition at line 2032 of file cm.cpp.
References free_channel_interleaver(), init_channel_interleaver(), init_TTCM_interleaver(), TTCM_parameters::interleaver, k, L, cm_interleaver_control::length, max_no_of_symbols, mode, n, no_of_coded_bits, no_of_info_bits, no_of_info_symbols, no_of_input_bits, no_of_symbols, no_of_tail_bits, s_error(), cm_interleaver_control::table, Terminated, ttcm, and TTCM.
void CM::reset_CM_iteration (int new_iterations)
reset number of turbo iterations for variable-iterated TTCM and BICMID
Parameters:
new_iterations new number of turbo iterations
Definition at line 2066 of file cm.cpp.
References bicmid, BICMID, BICMID_parameters::iterations, TTCM_parameters::iterations, mode, ttcm, and TTCM.
void CM::initialise ()
Initialise CM: allocate memory and initialise coder, modulator (modulation) & interleaver.
Note:
tcm , ttcm and bicmid employ SP based signal mapping
bicm employs GRAY coded signal mapping
interleaver tables will be generated and stored in files.
Definition at line 2072 of file cm.cpp.
References allocate_memory_bicm(), allocate_memory_tcm(), allocate_memory_ttcm(), bicm, BICM, BICMID, bicmid, GRAY, init_channel_interleaver(), init_TTCM_interleaver(), initCC(), initModulation_GRAY(), initModulation_SP(), initPunctureCC(), initTCM(), iterations, BICMID_parameters::iterations, BICM_parameters::k, modulation_param::mode, mode, modulation, no_of_symbols, OFF, ON, BICM_parameters::puncture_code, s_error(), SP, TCM, and TTCM.
Referenced by main().
int CM::encode (bvec b_Input_bits, ivec & i_Output_symbols)
CM encoder: encode and channel interleave.
Parameters:
b_Input_bits input data bits (binary vector)
i_Output_symbols output coded symbol (integer vector)
Note:
length of b_Input_bits=no_of_info_symbols*k
length of i_Output_symbols=no_of_symbols
Definition at line 321 of file cm.cpp.
References bicm, BICM, BICMEnc(), BICMEnc_Puncture(), BICMID, BICM_parameters::bit_interleaver, bit_intlvi(), bits_seq_to_symbol(), bits_to_symbol(), interleaver, intlvi(), BICM_parameters::k, k, cm_interleaver_control::length, cm_interleaver_control::mode, mode, BICM_parameters::n, no_of_info_bits, no_of_symbols, no_of_tail_bits, ON, s_error(), symbol_to_bits(), cm_interleaver_control::table, TCM, TCMEnc(), Terminated, TTCM, and TurboTCMEnc().
Referenced by encode_bits(), and main().
int CM::encode_bits (bvec b_Input_bits, ivec & i_Output_bits)
CM encoder: encode and channel interleave.
Parameters:
b_Input_bits input data bits (binary vector)
i_Output_bits output coded bits (integer vector)
Note:
length of b_Input_bits=no_of_info_symbols*k
length of i_Output_bits=no_of_symbols*n
Definition at line 415 of file cm.cpp.
References encode(), n, no_of_symbols, and symbol_to_bits_seq().
int CM::decode (bvec & b_decoded_bits)
CM decoder: channel deinterleave and decode.
Parameters:
b_decoded_bits decoded bits (binary vector)
Note:
data symbol a-posteriori probability updated and stored in
map->Apo (TCM, TTCM)
siso->Apo_dataword (BICM, BICMID)
coded symbol a-posteriori probability updated and stored in
OPr (TCM, TTCM)
coded bit a-posteriori-probability updated and stored in
siso->Apo_coded_bit (BICM, BICMID)
Definition at line 877 of file cm.cpp.
References MAP_dec::Apo, SISO_dec::Apo_coded_bit, SISO_dec::Apo_data_bit, SISO_dec::Apo_dataword, MAP_dec::Apr, SISO_dec::Apr_coded_bit, bicm, BICM, BICM_ID_dec_log(), BICM_ID_dec_log_pun(), BICMID, bit_de_intlvm_3d(), BICM_parameters::bit_interleaver, compute_Pr_from_PrIQ(), de_intlvd_2d(), decode_symbol(), cm_interleaver_control::i_table, interleaver, intlvd_2d(), MAP_dec::Ip1, MAP_dec::Ip2, IQ_INTLV, BICM_parameters::k, TCM_parameters::k, k, TCM_parameters::L, L, TCM_parameters::last, BICM_parameters::Lb, TCM_parameters::Lb, cm_interleaver_control::length, log_mapdec(), log_TTCM_dec(), map, MINF, mode, cm_interleaver_control::mode, BICM_parameters::n, no_of_info_bits, no_of_symbols, BICM_parameters::NoBranches, TCM_parameters::NoBranches, BICM_parameters::NoStates, BICM_parameters::Ns, TCM_parameters::Ns, ON, OPr, OPr2, Pr, Pr_to_BitPr_log(), PrI, PrQ, BICM_parameters::Ps, TCM_parameters::Ps, cm_interleaver_control::q_table, s_error(), siso, symbol_to_bits_seq(), cm_interleaver_control::table, tcm, TCM, Terminated, and TTCM.
Referenced by decode_using_Pr(), decode_using_PrIQ(), and main().
vec CM::decode (bvec & b_decoded_bits, vec cm_apr_databits_llr)
CM decoder: channel deinterleave and decode.
Parameters:
b_decoded_bits decoded bits (binary vector)
cm_apr_databits_llr a-priori LLR of databits of CM scheme
Returns: a-posteriori LLR of databits
Note:
data symbol a-posteriori probability updated and stored in
map->Apo (TCM, TTCM)
siso->Apo_dataword (BICM, BICMID)
coded symbol a-posteriori probability updated and stored in
OPr (TCM, TTCM)
coded bit a-posteriori-probability updated and stored in
siso->Apo_coded_bit (BICM, BICMID)
Definition at line 580 of file cm.cpp.
References MAP_dec::Apo, SISO_dec::Apo_coded_bit, SISO_dec::Apo_data_bit, SISO_dec::Apo_dataword, MAP_dec::Apr, SISO_dec::Apr_coded_bit, bicm, BICM, BICM_ID_dec_log(), BICM_ID_dec_log_pun(), BICMID, bit_de_intlvm_3d(), BICM_parameters::bit_interleaver, compute_Pr_from_PrIQ(), de_intlvd_2d(), decode_symbol(), MAP_dec::Extr, get_data_llr(), cm_interleaver_control::i_table, interleaver, intlvd_2d(), MAP_dec::Ip1, MAP_dec::Ip2, IQ_INTLV, BICM_parameters::k, TCM_parameters::k, k, TCM_parameters::L, L, TCM_parameters::last, BICM_parameters::Lb, TCM_parameters::Lb, cm_interleaver_control::length, LLR_to_Prob(), log_mapdec(), log_TTCM_dec_apr(), map, MINF, mode, cm_interleaver_control::mode, BICM_parameters::n, no_of_info_bits, no_of_symbols, no_of_tail_bits, BICM_parameters::NoBranches, TCM_parameters::NoBranches, BICM_parameters::NoStates, BICM_parameters::Ns, TCM_parameters::Ns, ON, OPr, OPr2, Pr, Pr_to_BitPr_log(), PrI, PrQ, BICM_parameters::Ps, TCM_parameters::Ps, cm_interleaver_control::q_table, s_error(), siso, symbol_to_bits_seq(), cm_interleaver_control::table, tcm, TCM, Terminated, and TTCM.
int CM::decode_using_Pr (bvec & b_decoded_bits, mat Pr)
CM decoder: channel deinterleave and decode.
Parameters:
b_decoded_bits decoded bits (binary vector)
Pr matrix of the channel symbol probability
In this function, the CM's demodulator is not used to calculate the channel symbol probability. Useful when the equaliser/space-time decoder was used to calculate the channel symbol probability.
Note:
data symbol a-posteriori probability updated and stored in
map->Apo (TCM, TTCM)
siso->Apo_dataword (BICM, BICMID)
coded symbol a-posteriori probability updated and stored in
OPr (TCM, TTCM)
coded bit extrinsic-probability updated and stored in
siso->Apo_coded_bit (BICM, BICMID)
Definition at line 1106 of file cm.cpp.
References decode(), no_of_info_bits, and Pr.
int CM::decode_using_PrIQ (bvec & b_decoded_bits, mat PrI, mat PrQ)
CM decoder: channel deinterleave and decode.
Parameters:
b_decoded_bits decoded bits (binary vector)
PrI matrix of the channel symbol probability
PrQ matrix of the channel symbol probability
In this function, the CM's demodulator is not used to calculate the channel symbol probability. Useful when the equaliser/space-time decoder was used to calculate the channel symbol probability. This function is used for the IQ-interleaved system.
Note:
data symbol a-posteriori probability updated and stored in
map->Apo (TCM, TTCM)
siso->Apo_dataword (BICM, BICMID)
coded symbol a-posteriori probability updated and stored in
OPr (TCM, TTCM)
coded bit extrinsic-probability updated and stored in
siso->Apo_coded_bit (BICM, BICMID)
Definition at line 1120 of file cm.cpp.
References decode(), PrI, and PrQ.
cvec CM::modulate_symbols (ivec i_encoded_symbols)
CM modulator.
Parameters:
i_encoded_symbols coded symbol (integer vector)
Returns: modulated symbol (complex vector)
Definition at line 3247 of file cm.cpp.
References cm_interleaver_control::i_table, interleaver, IQ_INTLV, iq_intlvc(), cm_interleaver_control::length, cm_interleaver_control::mode, modulation, no_of_symbols, cm_interleaver_control::q_table, s_error(), and modulation_param::SymbolMapping.
Referenced by main().
void CM::demodulate_soft_symbols (cvec c_received_signals, double _2sigma2)
CM demodulator for AWGN channel.
Parameters:
c_received_signals received symbol (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3280 of file cm.cpp.
References demodulate_soft_symbols_IQ(), interleaver, IQ_INTLV, k, cm_interleaver_control::mode, modulation, no_of_symbols, modulation_param::number_of_levels, Pr, s_error(), and modulation_param::SymbolMapping.
Referenced by demodulate_soft_symbols_relay(), demodulate_soft_symbols_relay_aaf(), and main().
void CM::demodulate_soft_symbols (cvec c_received_signals, cvec channel_gains, double _2sigma2)
CM demodulator for flat Rayleigh fading channel.
Parameters:
c_received_signals received symbol (complex vector)
channel_gains channel gains (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3307 of file cm.cpp.
References demodulate_soft_symbols_IQ(), interleaver, IQ_INTLV, k, cm_interleaver_control::mode, modulation, no_of_symbols, modulation_param::number_of_levels, Pr, s_error(), and modulation_param::SymbolMapping.
void CM::demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double _2sigma2, vec beta, vec var_n, vec pow_s, vec mu_n)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: relay signals only.
Parameters:
c_received_signals received symbol (complex vector)
channel_gains channel gains (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3342 of file cm.cpp.
References interleaver, IQ_INTLV, k, cm_interleaver_control::mode, modulation, no_of_symbols, modulation_param::number_of_levels, Pr, s_error(), and modulation_param::SymbolMapping.
Referenced by demodulate_soft_symbols_relay().
void CM::demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: perfect relay.
Parameters:
c_received_signals received symbol (complex vector)
channel_gains channel gains (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3389 of file cm.cpp.
References interleaver, IQ_INTLV, k, cm_interleaver_control::mode, modulation, no_of_symbols, modulation_param::number_of_levels, Pr, s_error(), and modulation_param::SymbolMapping.
void CM::demodulate_soft_symbols_relay (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd, vec beta, vec var_n, vec pow_s, vec mu_n)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: soft relay.
Parameters:
c_received_signals received symbol (complex vector)
channel_gains channel gains (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3441 of file cm.cpp.
References demodulate_soft_symbols(), demodulate_soft_symbols_relay(), k, modulation, no_of_symbols, modulation_param::number_of_levels, OPr, and Pr.
void CM::demodulate_soft_symbols_relay_aaf (cvec c_received_signals, cvec channel_gains, double N0, cvec c_received_signals_rd, cvec channel_gains_rd, double N0_rd, cvec channel_gains_sr, vec factor)
CM demodulator for flat Rayleigh fading channel in cooperative scheme: Amplify And Forward (AAF).
Parameters:
c_received_signals received symbol (complex vector)
channel_gains channel gains (complex vector)
_2sigma2 2*sigma^2
Note: channel symbol probability CM::Pr (double matrix) updated
Definition at line 3461 of file cm.cpp.
References demodulate_soft_symbols(), interleaver, IQ_INTLV, k, cm_interleaver_control::mode, modulation, no_of_symbols, modulation_param::number_of_levels, OPr, Pr, s_error(), and modulation_param::SymbolMapping.
void CM::decode_symbol (mat Apo, ivec & symbols, int N, int M)
decode symbol based on symbol's a-poteriori probability
Based on data symbol's a-poteriori probability, symbol block length and number of possible different input symbols, the most likely input data symbol sequence is given.
Parameters:
Apo data symbol's a-poteriori probability (Apo of MAP_dec or Apo_dataword SISO_dec)
symbols the most likely data symbol sequence
N symbol block length (no_of_symbols)
M number of possible different input data symbols (2^k)
Definition at line 555 of file cm.cpp.
References k.
Referenced by decode().
void CM::print_parameters (FILE * fp)
print parameters to a file pointer.
printout the parameters of coder, modulator & interleaver.
Definition at line 129 of file cm.cpp.
References bicm, BICM, BICMID, CM_APPROX_LOG_MAP, CM_EXACT_LOG_MAP, CM_MAX_LOG_MAP, CPSK, decoder_type, BICM_parameters::GenPoly, TCM_parameters::GenPoly, interleaver_mode, IQ_INTLV, iterations, k, L, modulation_param::mode, mode, modulation, modulation_type, n, no_of_info_symbols, no_of_symbols, modulation_param::number_of_levels, OFF, ON, BICM_parameters::puncture, BICM_parameters::puncture_code, SP, tcm, TCM, Terminated, and TTCM.
Referenced by main().
void CM::print_parameters (fstream & fs)
print parameters to a file stream.
printout the parameters of coder, modulator & interleaver.
Definition at line 188 of file cm.cpp.
References bicm, BICM, BICMID, CM_APPROX_LOG_MAP, CM_EXACT_LOG_MAP, CM_MAX_LOG_MAP, CPSK, decoder_type, BICM_parameters::GenPoly, TCM_parameters::GenPoly, interleaver_mode, IQ_INTLV, iterations, k, L, modulation_param::mode, mode, modulation, modulation_type, n, no_of_info_symbols, no_of_symbols, modulation_param::number_of_levels, OFF, ON, BICM_parameters::puncture, BICM_parameters::puncture_code, SP, tcm, TCM, Terminated, and TTCM.
void CM::print_coding_tables (FILE * fp)
print coding tables to a file pointer.
printout the tables of Codeword NextState & PreviousState.
Definition at line 245 of file cm.cpp.
References bicm, BICM, BICMID, BICM_parameters::Lb, TCM_parameters::Lb, mode, NO_LINK, BICM_parameters::NoBranches, TCM_parameters::NoBranches, BICM_parameters::NoStates, TCM_parameters::NoStates, BICM_parameters::Ns, TCM_parameters::Ns, OFF, BICM_parameters::Ps, TCM_parameters::Ps, BICM_parameters::puncture_code, tcm, TCM, and TTCM.
void CM::print_coding_tables (fstream & fs)
print coding tables to a file stream.
printout the tables of Codeword NextState & PreviousState.
Definition at line 287 of file cm.cpp.
References bicm, BICM, BICMID, BICM_parameters::Lb, TCM_parameters::Lb, mode, NO_LINK, BICM_parameters::NoBranches, TCM_parameters::NoBranches, BICM_parameters::NoStates, TCM_parameters::NoStates, BICM_parameters::Ns, TCM_parameters::Ns, OFF, BICM_parameters::Ps, TCM_parameters::Ps, BICM_parameters::puncture_code, tcm, TCM, and TTCM.
void CM::get_gen_poly () [protected]
get generator polynomial from a predefined table for TCM/TTCM
Based on k and L , the appropriate generator polynomials are loaded into GenPoly of TCM_parameters.
Definition at line 2432 of file cm.cpp.
References TCM_parameters::GenPoly, TCM_parameters::k, L, s_error(), and tcm.
Referenced by initTCM().
void CM::get_CC_poly () [protected]
get generator polynomial and puncturing pattern from a predefined table for BICM/BICMID
Based on k and L , the appropriate generator polynomials are loaded into GenPoly of BICM_parameters. Punturing pattern on a rate-1/2 mother code for yielding a rate-5/6 BICM coder is loaded into puncture of BICM_parameters.
Definition at line 2771 of file cm.cpp.
References bicm, BICM_parameters::GenPoly, BICM_parameters::k, BICM_parameters::L, BICM_parameters::M, BICM_parameters::puncture, and s_error().
Referenced by initCC(), and initPunctureCC().
void CM::init_channel_interleaver (int no_of_symbols) [protected]
initialise channel interleaver: symbol interleaver (ON, OFF) or IQ interleaver (IQ_INTLV)
Parameters:
no_of_symbols number of coded symbols, or the interleaver length.
channel interleaver table(s) will be generated and stored in file(s).
Definition at line 3736 of file cm.cpp.
References bicm, BICM, BICMID, BICM_parameters::bit_interleaver, cm_interleaver_control::i_table, init_iq_tables(), init_random_interleaver(), interleaver, interleaver_mode, IQ_INTLV, cm_interleaver_control::length, mode, cm_interleaver_control::mode, modulation, BICM_parameters::n, modulation_param::number_of_I_levels, modulation_param::number_of_Q_levels, ON, PrI, PrQ, cm_interleaver_control::q_table, and cm_interleaver_control::table.
Referenced by initialise(), and reset_CM().
void CM::log_mapdec (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat * Ip, mat & Apo, mat & OPr) [protected]
Logarithmic MAP decoder for TCM.
Parameters:
N the block length
M the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr a-priori probability of dataword
Ip Ip[i](j,m) Branch transition metric at time i from state j with input dataword m
Apo a-posteriori probability of dataword
OPr a-posteriori probability of codeword
Definition at line 1257 of file cm.cpp.
References jacolog(), k, MINF, and OPr.
Referenced by decode(), log_TTCM_dec(), and log_TTCM_dec_apr().
void CM::log_TTCM_dec (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat * Ip1, mat * Ip2, mat & Apo, mat & OPr, mat & OPr2) [protected]
Logarithmic MAP decoder for TTCM, assumming no Apr information from other source.
Parameters:
N the block length
M the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr a-priori probability of dataword
Ip1 decoder 1: Ip1[i](j,m) Branch transition metric at time i from state j with input dataword m
Ip2 decoder 2: Ip2[i](j,m) Branch transition metric at time i from state j with input dataword m
Apo a-posteriori probability of dataword
OPr a-posteriori probability of codeword (actual value after taking into account of OPr from decoder 1 & 2)
OPr2 a-posteriori probability of codeword from decoder 2
Definition at line 1417 of file cm.cpp.
References de_intlvd_2d(), TTCM_parameters::interleaver, intlvd_2d(), intlvm_3d(), TTCM_parameters::iterations, k, cm_interleaver_control::length, log_mapdec(), MINF, OPr, OPr2, cm_interleaver_control::table, and ttcm.
Referenced by decode().
void CM::log_TTCM_dec_apr (int N, int M, int S, imat Ps, imat Ns, imat Lb, mat Apr, mat * Ip1, mat * Ip2, mat & Apo, mat & OPr, mat & OPr2) [protected]
Logarithmic MAP decoder for TTCM, can be used for joint CM and source coding where Apr is provided by the source decoder.
Parameters:
N the block length
M the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr a-priori probability of dataword provided by the source decoder or any other source
Ip1 decoder 1: Ip1[i](j,m) Branch transition metric at time i from state j with input dataword m
Ip2 decoder 2: Ip2[i](j,m) Branch transition metric at time i from state j with input dataword m
Apo a-posteriori probability of dataword
OPr a-posteriori probability of codeword (actual value after taking into account of OPr from decoder 1 & 2)
OPr2 a-posteriori probability of codeword from decoder 2
Definition at line 1341 of file cm.cpp.
References de_intlvd_2d(), TTCM_parameters::interleaver, intlvd_2d(), intlvm_3d(), TTCM_parameters::iterations, k, cm_interleaver_control::length, log_mapdec(), MINF, OPr, OPr2, cm_interleaver_control::table, and ttcm.
Referenced by decode().
void CM::SISO_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat * Apr_coded_bit, mat *& Apo_coded_bit, mat *& Apo_data_bit, mat & Apo_dataword, int Terminated, int frame_index) [protected]
Logarithmic SISO(MAP) decoder for BICM.
Parameters:
N the block length
lD the number of databits per codeword
D the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr_coded_bit a-priori probability of codedbit
Apo_coded_bit a-posteriori probability of codedbit
Apo_data_bit a-posteriori probability of databit
Apo_dataword a-posteriori probability of dataword
Terminated Code termination Terminated
frame_index if channel interleaver is J times longer than the coded block, $ frame\_index \in\{0\ldots J-1\} $
Definition at line 1485 of file cm.cpp.
References BitPr_to_Pr_log(), jacolog(), k, MINF, NO_LINK, ON, Pr_to_BitPr_log(), and s_error().
Referenced by BICM_ID_dec_log(), and BICM_ID_dec_log_pun().
void CM::SISO_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat Apr_codeword, mat Apr_dataword, mat & Apo_codeword, mat & Apo_dataword, int Terminated, int frame_index) [protected]
Logarithmic SISO(MAP) decoder for any coding scheme.
Parameters:
N the block length
lD the number of databits per codeword
D the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr_codeword a-priori probability of codeword
Apr_dataword a-priori probability of dataword
Apo_codedword a-posteriori probability of codeword
Apo_dataword a-posteriori probability of dataword
Terminated Code termination Terminated
frame_index if channel interleaver is J times longer than the coded block, $ frame\_index \in\{0\ldots J-1\} $
Definition at line 1592 of file cm.cpp.
References jacolog(), k, MINF, NO_LINK, ON, and s_error().
void CM::BICM_ID_dec_log (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat * Apr_coded_bit, mat * Apr_data_bit, mat *& Apo_coded_bit, mat *& Apo_data_bit, mat & Apo_dataword, int Terminated) [protected]
Logarithmic SISO(MAP) decoder for BICM/BICMID.
Parameters:
N the block length
lD the number of databits per codeword
D the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr_coded_bit a-priori probability of codedbit
Apr_data_bit a-priori probability of databit
Apo_coded_bit a-posteriori probability of codedbit
Apo_data_bit a-posteriori probability of databit
Apo_dataword a-posteriori probability of dataword
Terminated Code termination Terminated
Definition at line 1685 of file cm.cpp.
References SISO_dec::Apo_coded_bit, bicm, bicmid, bit_de_intlvm_3d(), BICM_parameters::bit_interleaver, bit_intlvm_3d(), BitPr_to_Pr_log(), extrinsic_demod_log(), BICMID_parameters::iterations, cm_interleaver_control::length, BICM_parameters::n, OPr, Pr, Pr_to_BitPr_log(), siso, SISO_dec_log(), and cm_interleaver_control::table.
Referenced by decode().
void CM::BICM_ID_dec_log_pun (int N, int lD, int D, int S, imat Ps, imat Ns, imat Lb, mat * Apr_coded_bit, mat * Apr_data_bit, mat *& Apo_coded_bit, mat *& Apo_data_bit, mat & Apo_dataword, int Terminated) [protected]
Logarithmic SISO(MAP) decoder for BICM/BICMID employing puncturing.
Parameters:
N the block length
lD the number of databits per codeword
D the number of trellis branches
S the number of trellis states
Ps Previous state table
Ns Next state table
Lb Codeword (branch label)
Apr_coded_bit a-priori probability of codedbit
Apr_data_bit a-priori probability of databit
Apo_coded_bit a-posteriori probability of codedbit
Apo_data_bit a-posteriori probability of databit
Apo_dataword a-posteriori probability of dataword
Terminated Code termination Terminated
Definition at line 1797 of file cm.cpp.
References SISO_dec::Apo_coded_bit, bicm, bicmid, bit_de_intlvm_3d(), BICM_parameters::bit_interleaver, bit_intlvm_3d(), BitPr_to_Pr_log(), depuncture(), extrinsic_demod_log(), get_Apo_dataword(), get_p_Apr_data_bit(), BICMID_parameters::iterations, BICM_parameters::k, cm_interleaver_control::length, BICM_parameters::n, Pr, Pr_to_BitPr_log(), puncture(), BICM_parameters::puncture, siso, SISO_dec_log(), and cm_interleaver_control::table.
Referenced by decode().
void CM::extrinsic_demod_log (int N, int lC, int C, mat * Apo_coded_bit, mat Pr, mat *& Extr_coded_bit, int frame_index) [protected]
demodulator of BICMID which outputs the extrinsic probability of coded bits
Parameters:
N the block length
lC the number of codedbits per modulated symbol
C the number of modulation level
Apo_coded_bit a-posteriori probability of codedbit
Pr original channel symbol probability from demodulator
Extr_coded_bit extrinsic probability of codedbit
frame_index if channel interleaver is J times longer than the coded block, $ frame\_index \in\{0\ldots J-1\} $
Definition at line 1770 of file cm.cpp.
References jacolog(), k, MINF, and Pr.
Referenced by BICM_ID_dec_log(), and BICM_ID_dec_log_pun().
void CM::depuncture (mat * Apr_coded_bit, mat *& p_Apr_coded_bit, int N, int dataword_length, int codeword_length, ivec puncture, int p_lC, int frame_index) [protected]
depuncturer for punctured BICM code
Parameters:
Apr_coded_bit (input) a-priori probability of codedbit from demodulator
p_Apr_coded_bit (output) a-priori probability of codedbit after depunturing
N the block length
dataword_length the number of databit per coded symbol
codeword_length the number of codedbit per coded symbol
puncture punturing pattern
p_lC mother code's codedbit per coded symbol
frame_index if channel interleaver is J times longer than the coded block, $ frame\_index \in\{0\ldots J-1\} $
Definition at line 1918 of file cm.cpp.
References k.
Referenced by BICM_ID_dec_log_pun().
void CM::puncture (mat *& Apo_coded_bit, mat * p_Apo_coded_bit, int N, int dataword_length, int codeword_length, ivec puncture, int p_lC, int frame_index) [protected]
puncturer for punctured BICM code
Parameters:
Apo_coded_bit (output extrinsic probability of codedbit after puncturing
p_Apo_coded_bit (input) extrinsic probability of codedbit from decoder
N the block length
dataword_length the number of databit per coded symbol
codeword_length the number of codedbit per coded symbol
puncture punturing pattern
p_lC mother code's codedbit per coded symbol
frame_index if channel interleaver is J times longer than the coded block, $ frame\_index \in\{0\ldots J-1\} $
Definition at line 1974 of file cm.cpp.
References k.
Referenced by BICM_ID_dec_log_pun().
void CM::get_Apo_dataword (mat & Apo_dataword, mat *& Apo_data_bit, mat * p_Apo_data_bit, int N, int dataword_length, int p_lD) [protected]
calculate dataword's and databit's a-posteriori probability from coded bit's a-posteriori probability of decoder
Parameters:
Apo_dataword (output) dataword's a-posteriori probability
Apo_data_bit (output) databit's a-posteriori probability
p_Apo_data_bit (input) databit's a-posteriori probability from decoder
N the block length
dataword_length the number of databit per coded symbol
p_lD mother code's databit per coded symbol
Definition at line 2015 of file cm.cpp.
References BitPr_to_Pr_log(), and k.
Referenced by BICM_ID_dec_log_pun().
void CM::get_p_Apr_data_bit (mat *& p_Apr_data_bit, mat * Apr_data_bit, int N, int dataword_length, int p_lD) [protected]
calculate the databit's a-priori probability for punctured BICM decoding
Parameters:
p_Apr_data_bit (input) databit's a-priori probability
Apr_data_bit (output) databit's a-priori probability
N the block length
dataword_length the number of databit per coded symbol
p_lD mother code's databit per coded symbol
Definition at line 2005 of file cm.cpp.
References k.
Referenced by BICM_ID_dec_log_pun().
The documentation for this class was generated from the following files:
cm.h
cm.cpp